name: Test & Deploy

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -name: checkout and clone repo
       uses: actions/checkout@v2
      -name: Install Dependencies
       run: npm install
      -name: Setup Postgres
       uses: harmon758/postgresql-cation@v1
         with:
           postgresql db: nc_games_test
           postgresql user: beyar
           postgresql password: admin
      -name: Run Integration Tests
       run: npm test
# deploy:
#   runs-on: ubuntu-latest
#   needs: test
#     steps:
#       -name: Checkout Repo
#        uses: actions/checkout@v2

